cybersec:
  tools:
    bruteforce:
      path: "./tools/redteam-bruteforce/bin/redteam-bf-real"
      config-dir: "./tools/redteam-bruteforce/config/"
    keylogger:
      path: "./tools/stealth-keylogger/bin/optimized-keylogger"
      log-dir: "./tools/stealth-keylogger/logs/"
    android:
      adb-path: "/usr/bin/adb"
      apk-path: "./tools/android-monitor/app-debug.apk"
  
  ui:
    theme: "dark"
    auto-save: true
    max-results: 10000
    
  reports:
    output-dir: "./reports/"
    auto-export: false
    
logging:
  level:
    com.research.cybersec: DEBUG
    org.springframework: WARN
    javafx: WARN